---
- name: loop services
  hosts: all
  tasks:

  - name: start services
    service:
      name: "{{ item }}"
      state: started
    loop:
      - httpd
      - vsftpd
    register: thepackage

  - name: show list package
    debug:
      var: thepackage