---
- name: Install, start and enable vsftp
  hosts: all
  tasks:
  
  - name: Install vsftpd
    ansible.builtin.yum:
      name: vsftpd
      state: latest

  - name: Start vsftpd service
    ansible.builtin.service:
      name: vsftpd
      state: started

  - name: Enabled vsftpd service
    ansible.builtin.service:
      name: vsftpd
      enabled: yes

  - name: create readme file
    ansible.builtin.copy:
      content: "Welcome to FTP server"
      dest: /var/ftp/pub/README
      force: no
      mode: 0444
...
