---
- name: install, start and enable vsftpd
  hosts: all
  tasks:
          - name: remove vsftpd
            ansible.builtin.package:
                    name: vsftpd
                    state: absent
